btc_path = "btc"
cert_path = ""
db_url = "/etc/chaind/chaind.db"
eth_path = "eth"
home = "/etc/chaind"
rpc_port = 8080
use_tls = false
log_level = "info"

[log_auditor]
log_file="/var/log/chaind_audit.log"

[redis]
url="localhost:6379"